### PR TITLE
Adding new FAI window(2500-1500m)

### PR DESCRIPTION
**Pull request by azurefireice**
Added new FAI window button on track view: `FAI window 2500-1500m`

Changed name of previous FAI window to `Old FAI window 3000-2000m`

Changes for mobile and web versions

### CODE REVIEW

**Comment by azurefireice** [comment]
@skyksandr I would very much appreciate a review and a subsequent merge, as It would be wonderful to get that released by tomorrow evening. (sorry for being pushy)

**Comment by azurefireice** [comment]
Also if there is a way to launch UI locally so I can show screenshots of how it looks like-i'll gladly do that, just point me to manual. 
As I understand using `.env.example` makes almost no sense as I have no data and infra set up locally.

**Comment by azurefireice** [comment]
Thank you! What would it take to deploy the changes to production?

**Comment by skyksandr** [comment]
@azurefireice I've unified link texts between mobile and desktop and deploying it right now

**Comment by skyksandr** [comment]
@azurefireice Thanks a lot for your contribution! 🔥

**Comment by skyksandr** [comment]
@azurefireice changes deployed.

**Comment by azurefireice** [comment]
Thank you very much!
I had a couple more ideas for improvement.
Namely provide faster access to personal tracks in tracks section, without
a need to type name every time. Quick filter tweaking.

**Comment by skyksandr** [comment]
@azurefireice I'd personally consider adding this straight to new version as it no longer use `select2` library and offers more flexibility in filtering.

telegram-cloud-photo-size-2-5444923066015657344-y

If you're interested - I'd be happy to help you on getting fully functional developer environment on your local machine.

**Comment by azurefireice** [comment]
Thank you!
I would ask you to share some readmes and doc on setting up local dev env.
I'll try to do that on my spare time and help out with UI v2.0 on react

**Comment by skyksandr** [comment]
@azurefireice I'll try to prepare a manual in the beginning of next week.

**Comment by azurefireice** [comment]
Thank you a lot. We have quite a community here, and there are people who
would love to help out. I will make sure to distribute it to everyone
interested.

**Pull request merged**
